# configuration for kitten choose-files
# see (https://sw.kovidgoyal.net/kitty/kittens/choose-files/#configuration)

show_hidden true

sort_by_last_modified last

respect_ignores true


# keyboard maps

map alt+a   cd ~/.local/share/applications/

map alt+d toggle sort_by_dates

